/*************
 * Structure *
 *************/
CREATE TABLE lst__location_types(
    id INTEGER NOT NULL,
    label VARCHAR(255) NOT NULL,
    icon VARCHAR(255) NOT NULL,
    lang_code CHAR(2) NOT NULL,
    PRIMARY KEY(id, lang_code)
);

CREATE TABLE lst__set_types(
    type VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE lst__stages(
    stage VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE lst__genres(
    genre VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE location_descriptions(
    id INTEGER NOT NULL,
    description VARCHAR(255) NOT NULL,
    lang_code CHAR(2) NOT NULL,
    PRIMARY KEY(id, lang_code)
);

CREATE TABLE locations(
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    latitude DOUBLE NOT NULL,
    longitude DOUBLE NOT NULL,
    location_type INT NOT NULL REFERENCES lst__location_types(id),
    location_description INT REFERENCES location_descriptions(id)
);

CREATE TABLE artists(
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    name VARCHAR(255),
    genre VARCHAR(255) NOT NULL REFERENCES lst__genres(genre),
    origin VARCHAR(255) NOT NULL,
    picture_name VARCHAR(255),
    website VARCHAR(255),
    facebook VARCHAR(255),
    myspace VARCHAR(255),
    soundcloud VARCHAR(255),
    label VARCHAR(255),
    bio TEXT
);

CREATE TABLE sets(
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    begin_date INTEGER NOT NULL,
    end_date INTEGER NOT NULL,
    type VARCHAR(255) NOT NULL REFERENCES lst__set_types(type),
    artist INTEGER NOT NULL REFERENCES artists(id),
    stage VARCHAR(255) NOT NULL REFERENCES lst__stages(stage)
);

/********
 * Data *
 ********/
INSERT INTO lst__location_types (id, label, icon, lang_code) VALUES (1, "Toilettes", "marker_toilet", "fr");
INSERT INTO lst__location_types (id, label, icon, lang_code) VALUES (1, "Restrooms", "marker_toilet", "en");
INSERT INTO lst__location_types (id, label, icon, lang_code) VALUES (2, "Douches", "marker_shower", "fr");
INSERT INTO lst__location_types (id, label, icon, lang_code) VALUES (2, "Showers", "marker_shower", "en");
INSERT INTO lst__location_types (id, label, icon, lang_code) VALUES (3, "Eau potable", "marker_water", "fr");
INSERT INTO lst__location_types (id, label, icon, lang_code) VALUES (3, "(Drinkable) Water", "marker_water", "en");
INSERT INTO lst__location_types (id, label, icon, lang_code) VALUES (4, "Restaurants", "marker_restaurant", "fr");
INSERT INTO lst__location_types (id, label, icon, lang_code) VALUES (4, "Restaurants", "marker_restaurant", "en");
INSERT INTO lst__location_types (id, label, icon, lang_code) VALUES (5, "Bar", "marker_bar", "fr");
INSERT INTO lst__location_types (id, label, icon, lang_code) VALUES (5, "Bar", "marker_bar", "en");
INSERT INTO lst__location_types (id, label, icon, lang_code) VALUES (6, "Scène principale", "marker_stage", "fr");
INSERT INTO lst__location_types (id, label, icon, lang_code) VALUES (6, "Main stage", "marker_stage", "en");
INSERT INTO lst__location_types (id, label, icon, lang_code) VALUES (7, "Scène alternative", "marker_stage", "fr");
INSERT INTO lst__location_types (id, label, icon, lang_code) VALUES (7, "alternative stage", "marker_stage", "en");
INSERT INTO lst__location_types (id, label, icon, lang_code) VALUES (8, "Stand Hadra", "marker_hadra", "fr");
INSERT INTO lst__location_types (id, label, icon, lang_code) VALUES (8, "Hadra's stand", "marker_hadra", "en");
INSERT INTO lst__location_types (id, label, icon, lang_code) VALUES (9, "Camping", "marker_camp", "fr");
INSERT INTO lst__location_types (id, label, icon, lang_code) VALUES (9, "Camp", "marker_camp", "en");
INSERT INTO lst__location_types (id, label, icon, lang_code) VALUES (10, "Poste de secours", "marker_rescue", "fr");
INSERT INTO lst__location_types (id, label, icon, lang_code) VALUES (10, "Rescue center", "marker_rescue", "en");
INSERT INTO lst__location_types (id, label, icon, lang_code) VALUES (11, "Chillout", "marker_chillout", "fr");
INSERT INTO lst__location_types (id, label, icon, lang_code) VALUES (11, "Chillout", "marker_chillout", "en");
INSERT INTO lst__location_types (id, label, icon, lang_code) VALUES (12, "Navette", "marker_shuttle", "fr");
INSERT INTO lst__location_types (id, label, icon, lang_code) VALUES (12, "Shuttle", "marker_shuttle", "en");

INSERT INTO locations (latitude, longitude, location_type) VALUES (45.114371, 5.610150, 8); /* Stand Hadra */
INSERT INTO locations (latitude, longitude, location_type) VALUES (45.115044, 5.610304, 6); /* Scène principale */
INSERT INTO locations (latitude, longitude, location_type) VALUES (45.118143, 5.610199, 7); /* Scène alternative */
INSERT INTO locations (latitude, longitude, location_type) VALUES (45.111134, 5.606830, 1); /* Toilettes */
INSERT INTO locations (latitude, longitude, location_type) VALUES (45.113493, 5.608273, 1); /* Toilettes */
INSERT INTO locations (latitude, longitude, location_type) VALUES (45.115874, 5.609513, 1); /* Toilettes */
INSERT INTO locations (latitude, longitude, location_type) VALUES (45.116741, 5.610014, 1); /* Toilettes */
INSERT INTO locations (latitude, longitude, location_type) VALUES (45.116902, 5.609991, 3); /* Eau potable */
INSERT INTO locations (latitude, longitude, location_type) VALUES (45.115910, 5.609687, 3); /* Eau potable */
INSERT INTO locations (latitude, longitude, location_type) VALUES (45.113413, 5.608430, 3); /* Eau potable */
INSERT INTO locations (latitude, longitude, location_type) VALUES (45.113327, 5.608629, 2); /* Douches */
INSERT INTO locations (latitude, longitude, location_type) VALUES (45.117330, 5.610073, 4); /* Restaurants */
INSERT INTO locations (latitude, longitude, location_type) VALUES (45.116522, 5.609435, 4); /* Restaurants */
INSERT INTO locations (latitude, longitude, location_type) VALUES (45.116244, 5.610409, 4); /* Restaurants */
INSERT INTO locations (latitude, longitude, location_type) VALUES (45.114238, 5.609780, 5); /* Bar */
INSERT INTO locations (latitude, longitude, location_type) VALUES (45.117712, 5.610042, 5); /* Bar */
INSERT INTO locations (latitude, longitude, location_type) VALUES (45.116917, 5.609494, 11);/* Chillout */
INSERT INTO locations (latitude, longitude, location_type) VALUES (45.114072, 5.608847, 10);/* Poste de secours */
INSERT INTO locations (latitude, longitude, location_type) VALUES (45.113572, 5.610338, 9); /* Camping */
INSERT INTO locations (latitude, longitude, location_type) VALUES (45.112864, 5.609796, 9); /* Camping */
INSERT INTO locations (latitude, longitude, location_type) VALUES (45.116137, 5.609024, 12); /* Navette */

UPDATE locations SET location_description = 1 WHERE location_type = 12;
UPDATE locations SET location_description = 2 WHERE location_type = 11;

INSERT INTO location_descriptions VALUES (1, "Arrivée de la navette (site)",    "fr");
INSERT INTO location_descriptions VALUES (1, "Shuttle destination (site)",      "en");
INSERT INTO location_descriptions VALUES (2, "L'éveil des sens",                "fr");
INSERT INTO location_descriptions VALUES (2, "Hippie stuff",                    "en");

INSERT INTO lst__genres VALUES("Psytrance");
INSERT INTO lst__genres VALUES("Progressive");
INSERT INTO lst__genres VALUES("Full On");
INSERT INTO lst__genres VALUES("Dark Trance");

INSERT INTO lst__set_types VALUES("DJ set");
INSERT INTO lst__set_types VALUES("Live act");
INSERT INTO lst__set_types VALUES("Live band");

INSERT INTO lst__stages VALUES("Main stage");
INSERT INTO lst__stages VALUES("Alternative stage");

INSERT INTO "artists" VALUES (1, 'Efficient Energy', '', 'Lyon / France', 'ph_efficient_energy', '', 'https://www.facebook.com/pages/EFFICIENT-ENERGY/172876799413490', '', '', 'Oobe', 'Efficient Energy est Dj et compositeur depuis maintenant 8 ans. Violoniste puis batteur depuis son plus jeune âge, il découvre la musique électronique en 2000. Profondément marqué par la trance psychédélique, c’est donc tout naturellement qu’il se mit à en mixer, proposant à chacune de ses représentations un mix débordant d’efficacité, promouvant l’éclectisme et développant une énergie redoutable.');
INSERT INTO "artists" VALUES (2, 'Plasma Corp', '', 'Croatie', 'ph_plasma_corp', '', 'https://www.facebook.com/pages/Plasma-Corp/143427095686521', 'http://www.myspace.com/plasmacorp', '', 'SoundForm / Veleno Music', 'A la fin des années 90, Hrvoje Kimbauer a commencé à jouer de la musique en tant que DJ et à organiser des soirées underground. Peu de temps après son projet de musique psytrance Progressie appelé Plasma Corp est crée. Suivi par de nombreux titres et remixes, son premier album est sorti au début de 2012 et est basé sur le style morning. En plus de la musique, il promeut près de Zagreb (Croatie), la culture trance avec un rassemblement annuel en plein air.');
INSERT INTO "artists" VALUES (3, 'Si', '', 'Croatie', 'ph_si_', '', '', '', 'https://soundcloud.com/si-momento-demento', 'Momento Demento', 'Après être allé à un grand nombre de soirées techno, Si s’est retrouvé sur un petit festival psytrance en Croatie où la musique électronique a retenu toute son attention. Peu de temps après il a commencé à faire de petites soirées et à jouer en tant que Dj à Zagreb. Après avoir obtenu une certaine expérience, il a fondé le label Momento Demento basé à Zagreb dans le but de faire des soirées underground avec des lives act internationaux, d’importants sound system. Son style de musique peut se décrire comme une fusion de Full On et de musique psychédélique. Il s’est produit dans de nombreuses soirées et festivals en Croatie et à l’étranger.');
INSERT INTO "artists" VALUES (4, 'Manu', '', 'Gap / France', 'ph_manu', 'http://www.hadra.net', 'https://www.facebook.com/manuhadra/1659781943', '', 'https://soundcloud.com/manu-hadra', 'Hadra', 'Manu, bercé très jeune par la musique reggae, dub & ragga, s’intéresse aux sons électroniques vers la fin des années 90. Il s’est d’abord investi dans l’organisation d’évènements avec l’association grenobloise Hadra. La rencontre avec David alias Dj Leptit et la découverte d’artistes comme GOW, Jahbo, Ajja ou Evp, lui permettent au fil des années, d’affiner ses goûts musicaux. Il rejoint l’équipe des Djs du label Hadra Records en 2008. Grâce à une excellente technique, ses Dj set explosifs sont d’une efficacité redoutable!!');
INSERT INTO "artists" VALUES (5, 'Penta', '', 'Portugal', 'ph_penta', 'http://www.pentafiles.com', 'https://www.facebook.com/pentafiles/49536114684', 'http://www.myspace.com/pentafiles', 'https://soundcloud.com/penta', 'AuraQuake', 'Nikita Tselovalnikov, alias Penta, est le producteur psytrance du label AuraQuake et fait de la musique depuis 1988. Après avoir joué dans plus de trente pays à travers le monde, apparaissant de façon répétée dans tous les festivals majeurs tels que Boom, Voov, Universo Paralello, Full Moon et Burning Man, Nikita a acquis une réputation comme l’un des pionniers et innovateurs dans le monde de la psytrance. Le son unique et futuriste de Penta, un mélange de style Darkpsy, Full-On et Progressive a permis de rassembler des gens de différentes scènes. Ses tracks sont présents dans des dizaines de compilations et dans six albums « Pentafiles », « Funraiser », « Horn Please », « Portuguese Abduction », « Give MeFive! », and « All Shots Double ». Depuis 2008, Nikita effectue sa propre musique house electro sous le nom d’Azorsky.');
INSERT INTO "artists" VALUES (6, 'Satchel', '', 'Afrique du Sud', 'ph_satchel', 'http://www.freeradicalrecords.com', 'https://www.facebook.com/sachafreeradical/108670022571350', 'http://www.myspace.com/sachafreeradical', '', 'Free Radical Records', 'En 1995, Satchel commence à mixer sur la scène Underground goa trance à Cape Town en Afrique du Sud. Il a joué et s’est impliqué dans l’organisation dans de nombreux festivals comme le Mushroom Mafia, Alien Safari, Vortex, Party Possible... Il fait parti du label Free Radical Records. Ces influences ont crée un style unique sur la scène et ses projets sont en constante évolution.');
INSERT INTO "artists" VALUES (7, 'Shotu', '', 'Grenoble / France', 'ph_shotu', 'http://www.hadra.net', 'https://www.facebook.com/shotumusic/137121816332052', 'http://www.myspace.com/shotulive', '', 'Hadra', 'David, alias Shotu pour son projet live ou Dj Leptit lorsqu’il est derrière les platines, est un électron libre de la trance. Depuis 2003, Shotu est parti à la conquête du monde de la trance. Avec 2 albums « Jungle Expedition » et « Conception » et 2 compilations (Twisted Vision I & II) sortis sur Hadra Records, David est l’un des artistes les plus actifs du label. Son style très personnel et la puissance de ses sets l’ont d’ores et déjà emmené dans les plus grands festivals internationaux, pour le plus grand bonheur des festivaliers du Boom au Portugal, du Festival Universo Paralello au Brésil, Gemini aux Etats-Unis, Nautica en Russie ou encore Rythms of Peace au Maroc.');
INSERT INTO "artists" VALUES (8, 'Brain Driver', '', 'Valence / France', 'ph_brain_driver', 'http://www.fractalrecords.ch', 'https://www.facebook.com/BrainDriver.Official/159819477384392', 'http://www.myspace.com/braindriver', '', 'Fractal records', 'Sylvain alias Brain Driver a découvert la musique électronique en 1995 lors d’une rave dans le sud de la France. Très vite attiré par cet univers, il achète ses premières platines en 1997. Il commence à jouer dans de nombreuses free party et bars de nuit jusqu’en 2001, puis il décide de créer ses propres morceaux. En 2006, son projet psytrance « Brain Driver » est né. Depuis, il a joué dans un grand nombre de soirées aux côtés de grands artistes comme Talamasca, Absolum, Azax Syndrome, Bliss, Phatmatix, Hyper Frequencies, Ace Ventura, Highko, Laughing Buddha, Biokinetix.... pour n’en nommer que quelques-uns. Après le succès de son EP « Nocturnal Addictions », il travaille actuellement sur son premier album et sa première compilation.');
INSERT INTO "artists" VALUES (9, 'In Lak Ech', '', 'Mexique', 'ph_in_lak_ech', 'http://www.catalystrecords.org', 'https://www.facebook.com/inlakechmusic/100000567967046', '', '', 'Catalyst Records', 'In Lak Ech est composé de deux artistes Mr. Haffman et Mr. Hisrav qui ont assemblé leur style pour jouer de la trance à n’importe quel moment de la journée ou de la nuit, sur n’importe quel dancefloor avec des effets positifs garantis. Leurs solides et groovy lignes de basses, mixées dans une délicate frénésie de son psychédélique et de percussions font de In Lak Ech, l’un des plus solicité live mexicain du moment.');
INSERT INTO "artists" VALUES (10, 'Ganesh', '', 'Lyon / France', 'ph_ganesh', 'http://www.dreamandfly.fr', 'https://www.facebook.com/GaneshCatalystRecords/204359759711070', 'http://www.myspace.com/dreamandflyasso', 'https://soundcloud.com/sidganesh', 'Dream & Fly', 'Julien alias Ganesh découvre la Trance en 1997 lors du festival ZOOM à Zurich en Suisse. En 2005, il fonde l’association Dream & Fly à Lyon et organise des soirées pour promouvoir cette musique. Il se met aussi à faire de la déco pour les soirées. Son style Full-On Morning très dynamique, l’amène à jouer en France, Suisse et plus récemment au Népal (Shanti Jatra Festival, Universal Religion) il a pu jouer aux cotés d’artistes internationaux comme Hyperfrequencies, Ajja, Avalon, Neuromotor, Yab Yum, Driss, Galactik Wave, Journey, Phatmatix,... Depuis peu la découverte du label Mexicain Catalyst Records l’oriente vers une Full-On Morning plus sérieuse, plus psychédélique, mais tout aussi groovy et colorée.');
INSERT INTO "artists" VALUES (11, 'Ital', '', 'Chili', 'ph_ital_', 'http://www.anturecords.com', 'https://www.facebook.com/itallive/134885163228802', 'http://www.myspace.com/itallive', 'https://soundcloud.com/itallive', 'Antu Records / Free Spirit Records', 'Ital, musicien d’origine chilienne et Dj Psytrance est dans la musique plus de 14 ans. Son style se caractérise entre un Groove Full-On avec son propre style caractérisé, plein d’atmosphères, bien groovy et psychédélique. En 2007, il crée le premier label psytrance chilien appelé « Antu Records ». Avec 10 ans d’expérience, Ital a été présent dans les événements les plus importants du Chili comme Lollapalooza Festival et aussi dans quelques grands festivals reconnus dans le monde entier comme : Boom Festival (Portugal), Universo Paralello Festival (Brésil), Nagisa Music Festival (Japon), Fusion Festival (Allemagne), VuuV Festival (Allemagne), Fullmoon Festival (Allemagne), Vortex (Afrique du Sud), The Expérience (Thaïlande). Il a également partagé la scène avec des grands noms de la scène psytrance internationale actuelle de tous les continents.');
INSERT INTO "artists" VALUES (12, 'RA', '', 'Norvège', 'ph_ra', '', 'https://www.facebook.com/ratrance/34657276738', '', '', 'Suntrip records', 'Lors de sa création en 1994, RA était l’association de Christer Borge-Lunde et Lars W. Lind. Quatre ans plus tard, Chris continue en solo tandis que Lars travaille sur d’autres projets. En 1998, RA a signé avec Blue Moon Productions Royaume-Uni et a sorti son premier morceau Azure Child. En 1999 et 2000, RA a travaillé avec Blue Moon en Thaïlande et a collaboré avec Charlie Clarke pour son album « To Sirius ». L’album a d’abord été publié en Thaïlande en 2000 puis réédité en 2001 dans le monde entier par le label allemand Velvet / GTN. En 2006, Lars et Christer décident de travailler à nouveau ensemble. Vous pouvez les entendre sur l’album 9ème (Suntrip Records) et sur de nombreuses compilations. Un nouvel album est prévu en 2012.');
INSERT INTO "artists" VALUES (13, 'Tilt', '', 'Saint-Etienne / France', 'ph_tilt', 'http://www.hadra.net', 'https://www.facebook.com/tiltprog/507563099302643', 'http://www.myspace.com/tiltprogressive', 'https://soundcloud.com/tilt-hadra', 'Hadra', 'En 1995, Cyrille Licchese alias Chekk List débarque sur la scène Techno pour la première fois à St Etienne. L’année 2000 marque le passage de l’artiste d’une esthétique techno, new beats à l’univers de la psytrance et ainsi le remplacement de Chekk List pour le prometteur Sangohan! En 2003, après la création de son association, Transplosion, il fait son entrée sur le label anglais Free Spirit Records et sur le label Français Avigmatic Record comme Dj résident. Tilt intègre l’équipe Hadra en 2009, plus que jamais motivé pour participer activement au développement de la Trance en France et à l’étranger et à s’investir pour l’association.');
INSERT INTO "artists" VALUES (14, 'Cyrhill', '', 'Valence / France', 'ph_cyrhill', '', '', 'http://www.myspace.com/cyrhill', 'https://soundcloud.com/cyrhill', 'Omniphonie / Iono Music', 'Cyrhill alias Cyril Murtas a découvert la musique électronique en 1990 quand il était enfant. En 1992, il a commencé à avoir une collection de musique électronique de différents styles : house, techno, trance, acide, hardcore, etc ... Il découvre réellement la trance psychédélique en 1995 avec les grands noms de cette époque : Total Eclipse, Astral Projection, Doof, Transwave, Electric Universe ... Ses Dj sets sont dynamiques et puissants, groovy et émotionnels. Cyrhill a gagné plusieurs concours de Dj et a partagé plusieurs lives avec entre autres : The Commercial Hippies, Hyper Frequencies, Braincell, Symphonix, Klopfgeister, Invisible Reality, Egorythmia, Funky Dragon. Actuellement, Cyrhill fait partie de l’association Omniphonie qui organise des soirées autour de Lyon et de Valence depuis 2008. Fier de ses nombreuses expériences, il a intégré le célèbre label allemand de progressif, Iono music.');
INSERT INTO "artists" VALUES (15, 'Tenka', '', 'Danemark', 'ph_tenka', 'http://www.globalfoundation.dk', 'https://www.facebook.com/tenkatrance/196888405431', 'http://www.myspace.com/tenkatrance', 'https://soundcloud.com/tenkatrance', 'Global Foundation', 'Tenka a été initialement lancé en 2000 par Jesper Eskildsen alias Espark et Bjørn Jacobsen alias Cujurious One. Avec leurs tracks comme « Muggert » et « Broken Neck », ils se font vite un nom dans la scène Trance Progressive. En 2002, le groupe prend une pause dans le but de travailler sur des projets solos et de dj. En 2009 Tenka se recompose avec un troisième membre Lysholdt Ole alias Hiawata. Ensemble, ils sont prêts à conquérir le monde avec leur style Dark Progressive.');
INSERT INTO "artists" VALUES (16, 'Feuerhake', '', 'Allemagne', 'ph_feuerhake', '', 'https://www.facebook.com/djfeuerhake/303187641145', '', '', 'Plusquam / FreeForm Records', 'Basé à Hambourg, producteur et Dj, Stefan Feuerhake a commencé sa carrière musicale dans les années 1990, dans un style plus hip-hop et funk. Quelques années plus tard, il a été infecté par le virus de la techno, qui a complètement changé ses mixs. Par la suite, il s’est montré l’un des Djs les plus influents et populaires de la scène internationale trance progressive et psy-trance. Stefan alias Feuerhake a joué dans plus d’une vingtaine de pays. En 2001, il a été élu Dj de l’année par les lecteurs du Mushroom Magazine, le plus populaire magazine psy-trance dans le monde. En tant que producteur, Stefan a sorti quatre albums, quelques singles et de nombreuses collaborations et remixes. Son style, est un mélange de house progressive et de trance, mais son répertoire comprend Ambient et Chillout (et même depuis peu de hip-hop)');
INSERT INTO "artists" VALUES (17, 'Secret Vibes', '', 'Paris / France', 'ph_secret_vibes', 'http://www.secretvibes.fr', 'https://www.facebook.com/pages/SECRET-VIBES/72376177317', 'http://www.myspace.com/secretvibes', 'https://soundcloud.com/secret-vibes', 'Hadra', 'Le groupe français Secret Vibes est une formation électro-acoustique inspirée de sonorités aux horizons divers, entre musiques éthniques, lyrique et électro. Samplers, effets spéciaux, percussions, didgeridoos, flûtes & voix aux multiples facettes sont les ingrédients de ce groupe explosif. En live, le groupe collabore avec de nombreux musiciens, danseurs et performers et offre chaque fois un spectacle plein de fantaisie! En 2009, Secret Vibes fête son dixième anniversaire et sort, son dernier album « Firefly » aux couleurs progressives et « ethno psychédéliques » sur le label londonien Aboriginals Recordings. Depuis début 2011, Secret Vibes retrouve le label Hadra Records, pour de nouvelles aventures....');
INSERT INTO "artists" VALUES (18, 'Sine Die', '', 'Grenoble / France', 'ph_sine_die', 'http://www.hadra.net', '', 'http://www.myspace.com/sinedielive', 'https://soundcloud.com/sine_die', 'Hadra', 'Yohan Lasorsa, alias Noda ou Sine Die, a dans un premier temps abordé les musiques électroniques sous l’angle de la techno et de la house. En 2004, il crée Sine Die, un projet inspiré par les vibrations “old school” de la Goatrance et les puissantes sonorités psychédéliques de la scène psytrance actuelle. C’est dans cet univers qu’il produit plusieurs morceaux sur le label Hadra Records, avant de sortir, en 2008, son premier album « Life Hack ». Sine Die est l’alchimie de rythmes dynamiques et de sonorités colorées, pour le plus grand bonheur des amoureux de la goa et de la full-on!');
INSERT INTO "artists" VALUES (19, 'Lunarave', '', 'Chambéry / France', 'ph_lunarave', 'http://www.lunarave.com', 'https://www.facebook.com/lunaravefanpage/122274333592', '', 'https://soundcloud.com/lunarave', 'Hadra', 'Le cosmos, le voyage, le temps et l’Histoire... notions symboliques de l’univers de Lunarave... C’est en écumant, dès 2004, les scènes de la région Rhône-Alpes au sein des associations Psynap’s et Hadra (qu’il intègre en 2006 après une première release sur la compile Sunrise), que Lunarave fait connaître son style et sa griffe (Nuits Sonores 2008, Hadra Trance Festival, Ilha Bela, etc...)! Il livre aujourd’hui un live construit qui nous entraîne à travers l’éventail hypnotique de la psytrance et où les sons mystiques nous transportent pour « un voyage épique et intemporel sans retour »!');
INSERT INTO "artists" VALUES (20, 'Isochronic', '', 'UK', 'ph_isochronic', 'http://www.psynonrecords.com', 'https://www.facebook.com/pages/Isochronic/180230475363728', '', 'https://soundcloud.com/isochronic', 'Psynon Records', 'Isochronic est un projet trance réunissant Andreas Markitanis alias Centauro et Haris Demetriou alias Nomad 25, tout deux originaires de Chypre et vivant actuellement à Londres.  Amateurs de la trance depuis 1997, ils ont assisté à des soirées trance dans le monde entier. Andréas a été DJ connu internationalement sous le nom de Centauro et a aussi développé son propre projet solo sous le nom de Harmonic Rebel. Haris à quant à lui été DJ pendant de nombreuses années et il travaille actuellement intensivement sur son projet Nomad 25. Le projet Isochronic s’est formé à la suite d’une longue amitié. Andreas et Haris travaillent actuellement sur l’EP qui comprendra 3 tracks et qui sortira sur le label Psynon. Dans un avenir proche, ils sortiront un album qui refletera l’ensemble de leurs expériences de vie et leur passion pour la musique trance psychédélique.');
INSERT INTO "artists" VALUES (21, 'Toto', '', 'Carcassone / France', 'ph_toto', 'http://www.world-people.org/crew.php?artist=1&&lang=fr', '', 'http://www.myspace.com/piratedmachines', '', 'World People', 'Toto a commencé à collectionner de la musique au début des années 90 pendant ses voyages autour du monde. Fin 2002, lors d’un voyage en Afrique du Sud, il est contacté par Liquid Collective pour jouer à Ruthler Valley. Depuis il a joué en tant que Dj dans de nombreux pays et festivals comme Little Green Planet à Kent (Angleterre), Waterworld Festival (Croatie), au Portugal, en Espagne, en Grèce, en Russie. En 2005, il a commencé à apprendre à composer et à produire de la musique avec le projet Sound Pirates. Depuis, il a créé l’association World People et leur premier festival «  Révolution » qui a eu lieu en juillet 2006. 2011 voit la création de deux nouveaux projets : « Ze LooterS » avec Synaptick et « Skyhigh Pirates » avec Mark Skyhighatrist de Catawampus Rec.');
INSERT INTO "artists" VALUES (22, 'Mubali', '', 'USA', 'ph_mubali', '', 'https://www.facebook.com/pages/Mubali/50089873345', 'http://www.myspace.com/mubalitrax', 'https://soundcloud.com/mubali', 'Parvati Records', 'Mubali est le projet musical de Greg Farley. D’éducation musicale funk, soul et classique, il s’est impliqué dans la musique électronique depuis 2000 après avoir été converti à la culture Dj au Burning Man et aussi grâce à l’apprentissage de Dj Dice. En 2001, Dj Mubali est né et se produit sur les scènes françaises, russes et danoises. Il mixe auprès d’Ocelot, Random, Gheg on Earth, Chromatone, Penta... En 2003, Mubali apprend à produire et composer sa propre musique. Depuis Mubali a joué partout dans le monde et dans de nombreux festivals comme le Boom Festival et le Full Moon Festival. Il a sorti 2 albums chez Trishula Records. Son style peut être décrit comme parfois funky et sautillantes, morcelés et méchant, mais toujours psychédéliques. Actuellement, il a son propre projet solo et un autre projet avec Onkel Dunkel nommé Speakerhuggers (Parvati Records) qui a commencé à faire son apparition sur les dancefloors du monde entier.');
INSERT INTO "artists" VALUES (23, 'Cubic Spline', '', 'Grenoble / Rennes / France', 'ph_cubic_spline', '', 'https://www.facebook.com/CubicSpline/125368040871079', 'http://www.myspace.com/cubicspline', 'https://soundcloud.com/cubic_spline', 'Hadra', 'Passionné par la synthèse sonore, le duo Cubic Spline (Clément Bastiat et Olivier Richard) trouve son unicité dans des atmosphères dépaysantes et des textures sonores travaillées. Ils ont ainsi développé un son très mental et détaillé qui marie à merveille les racines de la trance goa, l’hypnotisme de la dark psytrance et la puissance des productions modernes. Le duo a rejoint l’équipe du label Hadra Records au début de l’année 2010 et, après une première release sur la compilation Hadracadabra 5 du label, Cubic Spline sort son premier EP « Unusual Path », en octobre 2010. Soyez prêts à ressentir les ondes puissantes d’un live psychédélique et transcendant !');
INSERT INTO "artists" VALUES (24, 'Sychotria', '', 'Brésil', 'ph_sychotria', '', 'https://www.facebook.com/sychotria/650565030', 'http://www.myspace.com/sychotria', 'https://soundcloud.com/sychotria', 'Ayauma Records', 'Sychotria, formé au début de 2007 par Charles et Cardoso, est un projet psychédélique Full-on. Charles se produit également sous le nom de Whiptongue tandis que son ami Flavio est également connu en tant que Xpiral. Sychotria a signé avec le label Ayauma Records (Brésil) et est présent sur diverses compilations comme Pagan Forest Magik, Tales From The Crypt, Enter Mitnal, Depth of Ankh, Zoomorphic Rituals, Ruthless Illusions, The Power Of Dreams... Sychotria est l’un des plus connus projets des nuits brésiliennes et a joué dans de nombreux nights club, des soirées et les grands festivals dans tout le Brésil : Samsara Festival, Festival de MG Out of Time, SoulVision Festival, Carnaval Festival, Paradise Festival.');
INSERT INTO "artists" VALUES (25, 'Chriss', '', 'Allemagne', 'ph_chriss', 'http://www.freqsofnature.de', 'https://www.facebook.com/DjChrissFullmoon/570432039', '', '', 'Fullmoon / Nutek Records', 'Chriss est Dj depuis 2002 et après plusieurs années à jouer dans le monde entier, il rejoint Nutek Records Espagne (Full-On) et Antu Records Chili (Psychédélique) en 2009. De plus, il a joué dans de nombreux festivals allemands comme Vuuv, Antaris, Spiritual Healing, Indian Spirit, Psychedelic Circus, Psychedelic Experience et à travers le monde : Life Festival (Irlande), Universo Paralello (Brésil), Soulclipse (Turquie), Ozora (Hongrie), entre autres. Il est également impliqué dans un tout nouveau projet allemand : Fullmoon Festival présente Freqs of Nature du 4 au 9 juillet 2012 près de Berlin.');
INSERT INTO "artists" VALUES (26, 'Plasmotek', '', 'Toulouse / France', 'ph_plasmotek', '', 'https://www.facebook.com/plasmotek/122598664429300', 'http://www.myspace.com/plasmotek', 'https://soundcloud.com/plasmotek', 'Mandala / 24/7 Records', 'Thibaut LAPEYRE est né en 1983, il a grandi à Paris en France. Sa passion et sa carrière musicale a débuté à l’âge de 5 ans quand il a décidé d’apprendre le piano dans une école de musique sur Paris. Plasmotek a commencé à mixer sur Paris dans les soirées trance underground et il a quitté Paris pour aller vivre sur Toulouse. En 2005 il sort son premier album Psytrance Techno « LiFted » sur le label de Mandala Records et peu de temps après il a été invité à jouer dans le monde entier. Aujourd’hui, PLASMOTEK vient de produire un nouvel EP « Unreal » avec 24/7 Records et va bientôt sortir un autre nouvel EP « Human Touch » chez Mandala Records !! Il a produit divers EPs sur des labels tels que Timecode records, Wired Music ... !!');
INSERT INTO "artists" VALUES (27, 'Cosmosis', '', 'UK', 'ph_cosmosis', 'http://www.cosmosis.co.uk', 'https://www.facebook.com/BillyCosmosis/792990466', 'http://www.myspace.com/cosmosis1', 'https://soundcloud.com/cosmosis-official', 'Holophonic Records', 'Avec une carrière commençant à Goa et avec 17 ans de production psytrance, Cosmosis est un des vétérans de la scène Trance. Il est l’un des artistes originaux de la musique Trance avec les célèbres Total Eclipse, Hallucinogen, Astral Projection et d’autres. Ils ont contribué à définir le nouveau son Goa et Psytrance dans les années 90. Ses premiers morceaux sont sortis sur l’album Cannabinoid en vinyle en 95 chez Transient Records. En 96, il sort l’album « The seminal Cosmology » qui fut un réel succès. Aujourd’hui cet album est considéré comme l’un des albums de référence en Trance-Goa. Durant 17 ans, Cosmosis joue régulièrement dans le monde : Japon, Brésil, Israël, Inde, Allemagne, Australie, Colombie, Afrique du Sud, Suède, Slovaquie, Angleterre, Irlande, Canada, Finlande, Hollande, Russie, France, Mexique et d’autres.');
INSERT INTO "artists" VALUES (28, 'Boom Shankar vs Alexsoph', '', 'Allemagne', 'ph_boom_shankar_vs_alexsoph', 'http://www.bmss.eu', 'https://www.facebook.com/DjBoomShankarBMSS/127214297356376', '', 'https://www.soundcloud.com/boomshankar-bmssrecords', 'BMSS Records', 'Armin Guenther alias Boom Shankar, après une initiation à Goa, a parcouru le monde depuis les années 90 en reflétant dans ses sets la mixité et la richesse de la scène psytrance. Label manager de BMSS Records, il a joué dans de nombreux festivals et soirées renommés tels que : Paradise Waterfalls (Thailande), Ozora (Hongrie) Antaris Project (Allemagne), Summer Never Ends Festival (Suisse), Full Moon (Thailande), Paradise Festival (Autriche), Black Moon (Italie), Mystica (Suisse)...Alexsoph est Alex Walter, né dans le sud de l’Allemagne, a commencé à jouer en Suisse dès le début des années 2000, avec des sets pumpy, groovy en ajoutant une pincé de psychédélisme. Cette année, ils sont réunis pour le festival Hadra, sur la même scène, et nous prépare un set unique orienté Full-On, pour une après-midi groovy au soleil !');
INSERT INTO "artists" VALUES (29, 'Nesho', '', 'Croatie', 'ph_nesho', 'http://www.djnesho.com', 'https://www.facebook.com/nenad.n.milacic/676795218', 'http://www.myspace.com/neshodj', 'https://soundcloud.com/neshodj', 'Tesseract Studio', 'Son amour pour la musique est passé par différents styles musicaux : le métal, le rock, hardcore, grind core, reggae… En 1994, il découvre la musique psychédélique avec la goa trance et la vague hippies des années 60. Peu après, il se rend à sa première goatrance party ou il fut impressionné par les couleurs, les décorations, le rôle des couleurs UV… En 1996, il décide de créer sa propre histoire avec la trance et se met aux platines. DJ Nesho est aussi le co-créateur de l’association audio-visuel « Mars Room » qui organise le festival Future Nature depuis plus de 12 ans. Il travaille maintenant avec le label Tesseract studio avec qui il a sorti sa première compilation Future Nature vol. 1 et Future Nature vol. 2 (aout 2011), introduisant de nouveaux standards sur la scène progressive.');
INSERT INTO "artists" VALUES (30, 'Osher', '', 'Israël', 'ph_osher', '', 'https://www.facebook.com/osherofficial', 'http://www.myspace.com/osherswissa', 'https://soundcloud.com/osher-blue-tunes', 'BlueTunes Recording', 'L’israélien a déjà fait ses preuves dans une série de grandes productions comme Amanda Shake ou D-Fusion. Son nouveau travail en solo qu’il présente sous le nom d’Osher se distingue par un remarquable caractère mature et indépendant. Dans son projet avec Blue Tune Records, il combine les deux horizons de son expérience musicale, représentée par ses précédents projets principaux. Le résultat est un crépuscule envoûtant entre le jour et la nuit, entre le repos et le suspense, entre Psychédélique et Progressive. Les arrangements complexes de ses morceaux sont composées d’une manière considérablement mélodique et disposent d’effets très subtils.');
INSERT INTO "artists" VALUES (31, 'ElekTrigger', '', 'Allemagne', 'ph_elektrigger', 'http://www.wald-frieden.de', 'https://www.facebook.com/djElekTrigger/294781733907277', 'http://www.myspace.com/elektrigger', '', 'Waldfrieder', 'ElekTrigger a grandi en Allemagne près de Waldfrieden, lieu bien connu pour son festival psytrance international « Wonderland ». Son amour pour la musique électronique a commencé après l’une des ces premières soirées techno à Waldfrieden dans le début des années 90. Après après avoir découvert le monde des musiques électroniques, il commença le mix. C’était donc juste une question de temps avant qu’il ne devienne un Dj de référence dans les soirées trance. Son style se situe entre la trance progressive et le psychédélique. Vous pourrez sentir l’influence techno dans sa musique et entendre le pouvoir de la trance.');
INSERT INTO "artists" VALUES (32, 'Funky Dragon', '', 'Serbie', 'ph_funky_dragon', 'http://www.ionomusic.com', 'https://www.facebook.com/pages/Funky-Dragon/366099380071877', 'http://www.myspace.com/funkydragon01', 'https://soundcloud.com/funky-dragon', 'Iono Music', 'Né en Serbie en 1977, Igor vit et produit à Vienne (Autriche) depuis l’année 2000. Intégrant une école d’audio-ingénierie, Funky Dragon acquiert de bonnes connaissances musicales sur lesquelles il construit sa propre sonorité croustillante et atmosphérique avec des arrangements intéressants. Sa première création musicale est sortie en 2004, suivie un an plus tard, par son premier album « The Algol » avec le label Synergetic Records. En 2007, il rejoint la famille Iono pour sortir son 2e album « Massive ». Sa musique peut être décrite comme groovy trance progressive avec des éléments funky et percutants.');
INSERT INTO "artists" VALUES (33, 'Balkan Beat Box', '', 'Israël / USA', 'ph_balkan_beat_box', 'http://www.balkanbeatbox.com', 'https://www.facebook.com/balkanbeatbox/22188167612', '', 'https://soundcloud.com/balkanbeatbox', 'Crammed Discs', 'Le Balkan Beat Box, groupe New-yorkais d’infatigables globe-trotteurs, fondé par des expatriés d’origine israélienne, a forgé sa réputation sur un mélange de musique balkanique (chants bulgares, fanfare serbe ou macédonienne), de touches orientales, de beats électro et un flow hip-hop, avant d’intégrer petit à petit de la cumbia et du reggae-dub. Composé d’un ancien du Gogol Bordello (Ori Kaplan), de l’ex-batteur des Firewater (Tamir Muskat) et rejoint ensuite par un chanteur explosif (Tomer Yosef), BBB aka Balakan Beat Box s’est ouvert à d’autres sonorités pour la sortie de leur 3ème album, Blue Eyed Black Boy, utilisant beaucoup de samples et de sons électroniques avec de vieux synthés et quelques instruments-jouets, tout en gardant son style caractéristique, en prise avec la réalité de son époque. Pour preuve, le titre « Part of the Glory », savant mélange entre Dj Mujava et le « King of Bongo » de la Mano Negra, traite des médias sociaux, de YouTube et de la notoriété que tout un chacun recherche. Il se fait tout aussi revendicatif et impliqué socialement avec  « Political Fuck », presque digne de Rage Against The Machine, en bien plus policé tout de même. Ceux qui n’adhéraient pas au BBB auparavant devraient être plus convaincu par ce nouvel album oeuvrant pour de nouveaux horizons musicaux, les autres se régaleront de ce nouvel album où les tubes jaillissent du porte-voix !');
INSERT INTO "artists" VALUES (34, 'D_Root', '', 'Chambéry / France', 'ph_d_root', 'http://www.d-root.com', 'https://www.facebook.com/fanpageDROOT/101117579959907', '', 'https://soundcloud.com/d_root', 'Hadra', 'Le projet D_Root, incarné par Aurélien Boijols, voit le jour à la fin des années 90. Influencé par certains pionniers comme Vibrasphere ou Liquid Soul, D_Root va s’imposer sur la scène trance régionale avec un style à part. Depuis son entrée sur le label Hadra Records en 2008, D_Root se fait connaître en France et au-delà, en Suisse et en Belgique où il partage la scène avec certains grands noms : HyperFrequencies, Gaudium, Lunaspice, etc. Son premier album « Root’Art », est sorti en 2010 sur le label Hadra Records.');
INSERT INTO "artists" VALUES (35, 'Psilocybian', '', 'Croatie', 'ph_psilocybian', 'http://www.psilocybian.com', 'https://www.facebook.com/psilocybian/100000869112530', '', 'https://soundcloud.com/psilocybian', 'Hyperflow Records', 'Sasha alias Psilocybian est bercé dès son plus jeune âge par la musique. A l’adolescence, il jouait de la basse et de la guitare électrique dans divers groupes. En 1999, il découvre la musique électronique et apprend petit à petit à produire ses propres morceaux. En 2009, il présente au public son premier CD incluant son premier album Wry Figments sorti plus tôt. De nombreuses sorties ont suivi et en 2012 il a signé son second album « Brain Dissolver » avec le label HyperFlow. Il participe à de nombreux projets musicaux tels que Dual Barrel, Footwork & SolidState et Mammal Project.');
INSERT INTO "artists" VALUES (36, 'Tweakers', '', 'Grenoble / France', 'ph_tweakers', 'http://www.hadra.net', 'https://www.facebook.com/pages/TWEAKERS/259475070741044', '', 'https://soundcloud.com/suddhashotu', 'Hadra', 'On ne présente plus Shotu, artiste novateur et référent du label Hadra Records, qui parcourt la France et le monde depuis 2002 dans les soirées ou festivals psytrance. C’est vers sa région d’origine, à Nantes, que Shotu rencontre Suddha, rassemblés par la musique électronique et notamment la découverte de la psytrance. Suddha a su avec le temps partager sa passion avec Shotu en lui apprenant les techniques du mix et de la composition. En 2004, ils sortent leur premier track grâce à l’aide de Jahbo qui leur a délivré les secrets du live. Dans leur volonté d’aller toujours plus loin, ils n’ont cessé de composer et de progresser ensemble, et cette année, ils ont décidé de créer le projet qui réunit leur deux univers, nommé Tweakers, sur le label Hadra Records.');
INSERT INTO "artists" VALUES (37, 'Southwild', '', 'Allemagne', 'ph_southwild', 'http://www.wildthingsrecords.co.uk', 'https://www.facebook.com/SOUTHWILD/826203101', '', 'https://soundcloud.com/SOUTHWILD', 'Wildthings Records', 'Jay est un producteur allemand de musique électronique. En collaboration avec son ami Ralph (Braincell / Solarspectrum), il fonde le projet psychédélique trance Rastaliens sur plus de 10 ans ... Au cours des années et à force de jouer dans les clubs et festivals à travers le monde, Rastaliens se fait connaitre par beaucoup de personnes. Southwild est le nouveau projet de Jay et en 2010, il rejoint les britanniques WildThings Records Label avec lequel il établit ce label psychédélique de trance positive et déjanté. Jay est prêt à sortir son 1er album « Synthologie » chez WildThings Records dans un proche avenir. Il a déjà présenté plusieurs morceaux sur des compilations de WildThings Records, Hadra, Looney Moon et Peak Records.');
INSERT INTO "artists" VALUES (38, 'Yab Yum', '', 'Suisse', 'ph_yab_yum', 'http://www.peakrec.com', 'https://www.facebook.com/pages/YabYum/230516163700464', '', '', 'Peak Records', 'Yab Yum est un projet psytrance de Suisse, formé en 2004 par Ajja et DJ Gaspard. Séduisant rapidement les amoureux de la psy du monde entier, ce duo est devenu célèbre pour ses grooves psychedelic, sa production impeccable et sa touche d’originalité. Ils ont sortis en 2006 le très apprecié album « Nocturnal Emissions » chez Peak Records ainsi que de nombreux tracts à travers le monde chez des labels de renom.  Ils ont joué dans la plupart des grands festivals et parties du monde entier, secouant et groovant les dance-floors.');
INSERT INTO "artists" VALUES (39, 'Dirty Saffi', '', 'UK', 'ph_dirty_saffi', 'http://www.bomshanka.com', 'https://www.facebook.com/dirtysaffi/145915725423644', 'http://www.myspace.com/dirtysaffimusic', 'https://soundcloud.com/dirtysaffi', 'Bom Shanka Music', 'Dirty Saffi est un couple à la vie comme sur la scène, composé d’Al, la moitié de Psymmetrix et Nuky, le DJ le plus talentueux chez Bom Shanka Music. Ils sont tout deux profondément amoureux de ces sons qu’ils estiment les plus mystiques et adaptés pour danser. Leur premier EP est sorti en 2010 et leur premier album « Beauty and the bitch » est prévu pour la fin de l’ été 2012.');
INSERT INTO "artists" VALUES (40, 'Moonquake vs Yamaga', '', 'UK / France', 'ph_moonquake', 'http://www.hadra.net', 'https://www.facebook.com/Moonquake.Hadra/442477859143096', 'http://www.myspace.com/nicomoonquake', '', 'Hadra', 'Moonquake découvre la psytrance en 1999 et commence à mixer peu de temps après à travers la France et l’Europe. Il participe à des soirées Hadra à Grenoble et dans les Alpes. En 2002, il  s’installe à Londres et trouve rapidement sa place parmi la communauté psytrance anglaise.. Avec l’aide de Jason Psylent en 2006, il devient co-producteur des Chrysalid parties. Sa première compilation « Epicentre » est sortie sur le label Hadra en juillet 2009. Moonquake a développé un style distinctif fortement influencé par le son Underground britannique. Ses sets changeants selon l’humeur des dancefloors sont toujours caractérisés par une atmosphère très psychédélique et une fluidité dynamique. Quant à Yamaga, passionné de musique électronique, il débute le mix fin des années 90 avec un mélange hard tek et trance. Les sonorités incroyables des Rastaliens, Pleiadians, Logic-Bomb ou encore TIP le font plonger dans l’univers psychédélique de la trance. Il rencontre en 2000 l’équipe de Spiritual Freequencies qui sera à l’origine de l’association Hadra en 2001 et dont il sera l’un des membres fondateurs. Dj résident du label Hadra Records dès 2009, son univers musical arbore les sons psychés et les ambiances colorées de la scène psytrance anglaise.');
INSERT INTO "artists" VALUES (41, 'Whiptongue', '', 'Brésil', 'ph_whiptongue', '', 'https://www.facebook.com/sychotria/650565030', 'http://www.myspace.com/whiptongue', 'https://soundcloud.com/sychotria', 'Looney Moon Records', 'Charles Matos alias Whiptongue est impliqué dans la musique électronique depuis 1999. Whiptongue a participé à une association qui a aidé à développer et à divulguer la trance psychédélique au Brésil. En 2000, il se consacre à acquérir des connaissances dans le domaine de la production psytrance et débute comme Dj au festival Samsara (Brésil). Son premier projet « Charivari » est sorti en 2002. Depuis 2007, il fait également parti projet Sychotria avec Xpirial.');
INSERT INTO "artists" VALUES (42, 'Digital Talk', '', 'Paris / France', 'ph_digital_talk', '', 'https://www.facebook.com/digital.talk.project/146056435410234', 'http://www.myspace.com/digitaltalk', 'https://soundcloud.com/digitaltalk', 'Hadra', 'Après avoir expérimenté sous plusieurs formes la musique acoustique, les deux amis d’enfance Julien Fougea et Luc Achintres ont été piqués par le virus Techno des années 90. Après 3 ans de travail au sein du quatuor Droidsect, monté en 98, Julien et Luc décident de continuer l’épopée en duo en créant, en 2001, Digital Talk, qui deviendra l’un des duos psytrances le plus reconnu en France et sur la scène psytrance mondiale. Après 6 ans de maxis ravageurs et un album « New Age Surf » sorti en 2004, le duo revient en 2010 avec un nouvel opus très attendu, « Audio Extremist » sur le label français Hadra Records.');
INSERT INTO "artists" VALUES (43, 'Brainiac', '', 'Croatie', 'ph_brainiac', '', 'https://www.facebook.com/brainiac.official/121294947905621', 'http://www.myspace.com/brainiacmusic', 'https://soundcloud.com/brainiac', 'Grasshopper / Solar Tech Records', 'Brainiac alias Philipp Cepetic, commence à jouer au début du millénaire en tant que Dj et écrit, après quelques années ses propres compositions. Rapidement il se produit sur des labels tels que : Wakyo Records, Spun, 24/7, Perfecto, Grasshopper Records, Catalyst Records, Solar Tech Records & Vagalume Records, surprenant ces labels par la clarté et la qualité de ses compositions. En combinant des rythmiques futuristes à des sons high-tech tout en gardant l’essence des mélodies et des atmosphères de la trance psychédélique, il participe à des événements tels que : Universo Paralello (Brésil), Nagisa Music Festival (Japon), Urban Art Forms (Austriche), etc...');
INSERT INTO "artists" VALUES (44, 'Driss', '', 'France', 'ph_driss', 'http://www.hadra.net', 'https://www.facebook.com/pages/Dj-Driss-Hadra/174923559253391', 'http://www.myspace.com/djdriss_hadra', 'https://soundcloud.com/dj-driss-1', 'Hadra', 'Driss est un Dj emblématique du label Hadra Records et l’un de ses fondateurs. Son expérience de la scène trance en France et à l’international, en qualité d’organisateur ou pour ses Dj sets acclamés dans certains des plus grands festivals mondiaux (Ozora en Hongrie, Nautica en Russie, Transahara au Maroc et bien d’autres), n’a cessé de nourrir son attachement pour la Trance goa, un style musical auquel il s’identifie pleinement. Depuis l’aventure de l’association Spiritual Freequencies dont il est l’un des initiateurs, il participe à la création et au développement de l’association Hadra, de son label et de son festival!');
INSERT INTO "artists" VALUES (45, 'U-Recken', '', 'Israël', 'ph_u_recken', 'http://www.electreelife.com', 'https://www.facebook.com/urecken/112993598724978', '', '', 'Dacru Records', 'Depuis la sortie de son premier album « Aquatic Seranade » chez Booflex Records en 2006 et après quelques sorties chez Doof Records, U-Recken a silloné le monde. Ses mélodies profondes et puissantes et son atmosphère psychédélique ont contribué à son succès dans les soirées israeliennes. Cela s’est confirmé lors de la sortie de son deuxième album studio « Deeper into man » qui a placé U-Recken comme l’un des plus grands artistes de la scène trance actuelle. En tant que musicien, il nous rappelle la vraie nature de cette musique qui n’est pas seulement un assemblage de trucs sonores pour nous faire danser, mais est vraiment une expérience psychédélique pour l’esprit et l’âme. Actuellement, U-Recken construit son label Tree of Life qui donnera bientôt naissance à son troisième album studio.');
INSERT INTO "artists" VALUES (46, 'Barak', '', 'Mexique', 'ph_barak', 'http://www.hadra.net', '', 'http://www.myspace.com/fernandobarak', 'https://soundcloud.com/barak-psytrance', 'Hadra', 'Fernando Diaz Gallardo alias Barak, a débuté à l’âge de 15 ans, sa carrière comme musicien en étant influencé par la scène Trance. Il créa son projet dans un unique but : Transmettre l’énergie et les émotions de la Trance.  Depuis Barak a joué dans des festivals et des soirées comme Earth Dance Mexico, Green Dreams Festival, Talamasca, Mikology Festival, Nierika, Yabai Summer Festival, Hadra Trance Festival, Australia Bushkatz, et dans bien d’autres. Il est devenu, au fil des années, le plus écouté et le plus booké de la scène Full-On mexicaine. N’hésitez pas à venir découvrir et kiffer son style hard, groovy et mystérieux que ce soit de nuit ou de jour.');
INSERT INTO "artists" VALUES (47, 'Freedom Fighters', '', 'Israël', 'ph_freedom_fighters', 'http://www.hommega.com', 'https://www.facebook.com/freedomfightersofficial/101969543173829', '', 'https://soundcloud.com/freedomfighters', 'HOM-Mega', 'Shahaf Efrat a pour nom de scène Freedom Fighters. Sa musique  est une nouvelle vague de la musique psytrance progressive mélangé à de la techno et avec des influences Drum & bass. La complexité de sa musique et son génie musical est sur de saisir n’importe quel danseur du dancefloor. Réjouissez-vous,  Freedom Fighter continue à s’imposer comme l’un des principaux producteurs électroniques de demain.');
INSERT INTO "artists" VALUES (48, 'Kokmok', '', 'Marseille / France', 'ph_kokmok', 'http://www.hadra.net', 'https://www.facebook.com/djkokmok/657012658', 'http://www.myspace.com/djkokmok', 'https://soundcloud.com/kokmok-hadra', 'Hadra', 'Aujourd’hui Dj représentant de l’univers de la Trance Progressive sur le label Hadra Records et programmateur du Hadra Trance Festival, Didier Pulcini, alias Kokmok est à l’origine issu de la scène techno et house du sud de la France. Elément clé dans le développement du label, Kokmok sortira sa première release en 2008 : « Obsessiv Progressiv » est alors le fruit d’une collaboration avec Echotek, Aerospace, Funky Dragon, Ovnimoon ou encore Ritmo. C’est le début d’une belle aventure qui le conduira sur les plus beaux dancefloors européens où Kokmok confirmera son style : basses prog et rythmes groovy au rendez-vous!');
INSERT INTO "artists" VALUES (49, 'Symbolic', '', 'Israël', 'ph_symbolic', '', 'https://www.facebook.com/symbolicmusic/190178034368718', '', 'https://soundcloud.com/symbolicmusic', 'Echoes Records', 'Symbolic s’est crée en 2011 avec l’association de Ilan Shemi et Oshry Ben Simon alias Dj Osho. Depuis leur première production, ils ont obtenu d’incroyables retours des danseurs du dancefloors tout autour du monde, et immédiatement les labels se sont montrés très intéressés par leur collaboration. Leurs premiers tracks « Crystal Clear » sont sortis sur une compilation « Dance Computer » d’Iboga Records, compilée par l’un des meilleur Dj’s Trance Progressive et producteurs, Ace Ventura. Deux morceaux, l’un avec Liquid Soul appelé « Différent Reality » et l’un avec Sphera appelé « One Step Closer », sont sortis sur Iboga Records dans une double compilation « Groove Attack » compilé par Liquid Soul.');
INSERT INTO "artists" VALUES (50, 'Gaudium', '', 'Suède', 'ph_gaudium', 'http://www.iboga.dancefoundation.nl/artists/gaudium', 'https://www.facebook.com/gaudiummusic/93797638111', '', 'https://soundcloud.com/gaudium', 'Iboga Records', 'Gaudium est le projet solo d’Andreas Wennerskold. Son troisième album « Session of progressions » sorti chez Iboga a vu le jour l’été dernier et a été très bien reçu dans les circuits de la trance progressive. Gaudium est régulièrement en tournée pour des concerts à travers le monde et est un excellent Dj. Parmi ses autres productions, on peut citer la collaboration avec Ace Ventura pour le titre « In Between », incluant un remix complètement fou de Capitain Hook. Le nouveau single de Gaudium est sorti en mars 2012 et comprend les morceaux « Mélodies Torn » et « Inside the box ». Venez découvrir une valeur montant de la Full-On !');
INSERT INTO "artists" VALUES (51, 'Vaishiyas', '', 'Allemagne', 'ph_vaishiyas', 'http://www.vaishiyas.de', 'https://www.facebook.com/vaishiyassync/80920413009', 'http://www.myspace.com/vaishiyassync', '', 'SpinTwist Records', 'Après des années de guitare, Hannes Klitta alias Vaishiyas a découvert sa passion pour la musique électronique en 1999. Son élan soudain a été propulsé avec la chanson « Schaukelstuhl » qui représente très bien le son de Hambourg. Du fait de la sortie de son premier album avec le label Jum Jam Records, il a été propulsé sur le devant de la scène trance progressive. Aujourd’hui, il est mentionné comme un grand nom de ce style. Il a joué dans les festivals comme Boom, Universo Paralello..');
INSERT INTO "artists" VALUES (52, 'Lakay', '', 'Grenoble / France', 'ph_lakay', 'http://www.lakaymusic.net', 'http://www.facebook.com/pages/lakay', 'http://www.myspace.com/lapsykay', '', 'Hadra', 'Trompettiste et multi-instrumentiste, c’est dans les années 2000 que Lakay découvre les musiques électroniques en côtoyant les free-parties. Issu d’influences à la fois traditionnelles et undergrounds, son live nous propose un doux voyage vacillant entre le dub & dubstep, la trance downtempo et la jungle psychédélique. Les boucles électroniques se mêlent aux mélodies de la trompette jazz, du seung thaïlandais ou encore au groove des guitares espagnoles autour d’un métissage vivant et coloré. Artiste à découvrir et à redécouvrir sans modération, sur scène et en écoute chez Salamah Productions et Hadra Records.');
INSERT INTO "artists" VALUES (53, 'Metastaz', '', 'Lyon / France', 'ph_metastaz', '', 'http://www.facebook.com/metastazmusic', 'http://www.myspace.com/metastazmusic', '', 'Tazart Music Netlabel', 'En tant que militant de la scène dub sur Lyon depuis les huit dernières années, Thomas Simoes alias Metastaz, combine inspiration ethnique et rythmes habiles, brisant ainsi les frontières des genres musicaux. Sa musique déssine un monde captivant dub électro dans lequel des tons mélanés et des influences urbaines s’entremèlent puis fusionnent. Il est facile de voir comment l’esprit de ce jeune artiste inspirée est toujours à la recherche de nouveaux tracts depuis qu’il a commencé à jouer avec ses claviers qu’il expérimente à travers des centaines de nuits blanches.');
INSERT INTO "artists" VALUES (54, 'Tor.Ma in Dub', '', 'Mexique', 'ph_tor.ma_in_dub', '', 'http://www.facebook.com/tormaindub', '', '', 'Catalyst Records', 'Musicien, producteur et Dj, Rafael Hernández, a commencé sa carrière dès son jeune âge en jouant de la batterie et de la basse dans plusieurs groupes de rock. Puis, à la fin des années 1990 il trouve sa vocation : Dj. Deux ans plus tard, il fusionne la trance goa avec de la musique mexicaine ethnique, qu’il a mis des années à expérimenter, en travaillant dur, jusqu’à ce qu’il trouve finalement une façon tout à fait nouvelle pour exprimer quelque chose de plus profond. C’est ainsi qu’il se tourne, en 2004, en composant la musique qui le rend plus libre et le plus enthousiaste : le chillout. En 2006, il crée son projet, Tor.Ma in Dub. Pour lui la seule bonne ambiance, le seul son afin de passer un bon moment et de mettre un sourire sur nos visages, à danser, à voyager ou se détendre est le mélange d’un old skool roots dub avec une pincée psychédélique.');
INSERT INTO "artists" VALUES (55, 'Ambient Terrorists', '', 'Grèce', 'ph_ambient_terrorists.png', '', 'http://www.facebook.com/fishimself', '', '', 'It Records', 'Ambient Terrorists est le projet commun de Haris Papadimitriou alias Fishimself d’Ultimae records qui a réalisé en 2011 la compilation « Ambrosia » sur Ultimae et de Dj C.op l’un des plus étonnant Dj d’Athènes. Ensemble, ils forment un superbe duo, créant une atmosphère unique, oscillant entre ambiant et downtempo.');
INSERT INTO "artists" VALUES (56, 'Dario Cosmos', '', 'Lyon / France', 'ph_dario_cosmos', '', 'http://www.facebook.com/d.cosmos', 'http://www.myspace.com/581098450', '', 'Massive', 'Dario Cosmos alias Aurélien Lance est issu de la scène Indus grenobloise, sous le nom de Led Medusa, il évolue peu à peu, dès le début des années 90, sous l’influence de l’électronique. Fan de musique électronique dans toute sa variété, il puise ses influences dans tous les styles. Mélange d’électro, de house, d’ambiant et de techno minimale, le son de Dario Cosmos est avant tout taillé pour le dancefloor, propulsant des rythmiques légères mais puissantes, nappées de mélodies tournoyantes et organiques. La musique de Dario Cosmos est une invitation au voyage, mais un voyage mené par la danse.');
INSERT INTO "artists" VALUES (57, 'Dolva', '', 'Croatie', 'ph_dovla', 'http://www.dovla.info', 'http://www.facebook.com/dovlaaa', '', '', 'Flow Records / Interchill', 'Dovla est un touche à tout. Tout d’abord Dj en passant par la programmation de festival, la gestion de scène pour A&R, la création de compilations et enfin le design graphique, il rejoint en 2010 Flow Records et aide maintenant à gérer ce label avec Pena. En tant que Dj, Dovla a joué dans les plus importants festivals européens tels que : Ozora (4 fois), Voov festival, Sonica, Indian Spirit, Tshitraka, Aurora et tant d’autres. Pendant 4 ans, il aida à organiser le célèbre festival Trance de Croatie « Underwater Overground ».');
INSERT INTO "artists" VALUES (58, 'Sysyphe', '', 'Montpellier / France', 'ph_sysyphe', 'http://www.hadra.net', 'http://www.facebook.com/sysyphe.hadra1', 'http://www.myspace.com/sysysphe', '', 'Hadra', 'C’est au milieu des années 90 que l’univers musical de Philippe Contamin, alors baigné dans les sonorités sombre du rock gothique qu’il incarne au chant et à la basse, croise les chemins de la musique électronique avec des groupes comme The Orb ou Solar Quest. Après son entrée sur le label Hadra Records comme artiste représentant de l’univers ambient, Sysyphe, sort une première compilation, « Hadravision », née d’une collaboration avec Nun et qui rassemble la crème de la crème avec Adham Shaikh, Aes Dana, ou encore Irina Mikhailova et Kick Bong. En 2010, il sort son premier album « Running up that hill » qui confirme le métissage de ses influences gothiques avec l’univers ambient psychédélique.');
INSERT INTO "artists" VALUES (59, 'Iain Dub', '', 'UK', 'ph_iain_dub', '', 'http://www.facebook.com/iain.dub', 'http://www.myspace.com/iaindub', '', 'SomethinGroovy', 'Iain Dub s’est impliqué dans la musique, depuis la fin des années 80, à travers Roots music. Il commença à DJing dans les soirées anglaises de Londres au début des anées 90. Puis, il a joué avec Alchemy Rec, Glastonbury, In Spiral, Glade, Sunrise, Liquid Rec, Phantasm, Wild Things, Wing Makers et Acide Monkey et dans le monde entier : Universo Paralello (Brésil),  Phantasm Records (US), Ozora (Hongrie), Black Moon (Italie), Phangan Magic Family (Thaillande)…. Attendez-vous à une musique super groovy pour les scènes d’ambient ou les dancefloors.');
INSERT INTO "artists" VALUES (60, 'Gabriel le Mar', '', 'Allemagne', 'ph_gabriel_le_mar', 'http://www.le-mar.de/gabriel-le-mar/', 'http://www.facebook.com/gabriellemarofficial', 'http://www.myspace.com/gabriellemar', '', 'Dub2dust Records', 'Gabriel Le Mar est un vétéran de la musique électronique avec plus de 30 productions d’albums à son actif. Dans son processus de création, l’artiste aime intégrer différentes constellations artistiques avec des pseudonymes tels que des projets Saafi Brothers, Aural Float ou Subsonic Park, et aussi coopère avec des artistes tels que Dr Motte ou Pete Namlook. Gabriel a également travaillé avec Aural Float pour l’album « Spacenight », sur ​​des concepts audiovisuels qui sont devenus un succès historique sur la télévision allemande et a été acclamé au niveau international et demeure, encore aujourd’hui, une référence chillout. Il vient de sortir son nouvel EP sur le label Dub2Dust Records « What´s your sleeper ? »');
INSERT INTO "artists" VALUES (61, 'Arketype Project', '', 'Tahïti', 'ph_arketype_project', 'http://www.arketypeproject.com', 'http://www.facebook.com/mahana.label', 'http://www.myspace.com/arketypeproject', '', 'Mahana Bay Label', 'Vanessa Esposito, artiste Polynésienne, présente un projet musical pluriethnique intitulé : Arketype Project. Depuis 2002, elle se produit sur les scènes européennes et du Pacifique du Sud, riche de ses expériences scéniques. Elle offre une vision harmonieuse des sons, des rythmes et du mouvement. Fusion d’un univers musical ethnique et technologique Vanessa participe à des compositions de musique d’avant-garde. Ses créations contemporaines et contrastées puisent dans la mémoire universelle musicale et réalisent le mixage entre le son authentique des instruments traditionnels du Pacifique Sud et l’étonnante diversité des nouvelles technologies. C’est dans cette résonance que le concept artistique d’Arketype Project propose un voyage musical où se mêlent atmosphères polynésiennes, rythmiques puissantes, sonorités ethniques scandées par des tempos tribaux, transes, psychédéliques, fusion et rock-électro.');
INSERT INTO "artists" VALUES (62, 'Tagada', '', 'Paris / France', 'ph_tagada', '', 'http://www.facebook.com/pages/DJ-TAGADA-officiel/113201495431807', '', '', 'Delalune', 'DJ Tagada, grâce à la révolution du Dance Floor à coups de Montagnes Russes, Fanfares des Balkans, Gypsy Punk, Electro Tzigane, Hip Hop Klezmer, Balkan Ragga ! En avant pour le télescopage entre sonorités actuelles et folklore, la vibration d’une corde de violon qui grince ou le son d’une trompette brûlante et moite : voilà ce qui donne la saveur et l’énergie du Dj Set du Gadjo Tagada. Profitez du dancefloor pour un bal électro complètement à l’Est pimenté aux saveurs balkaniques.');
INSERT INTO "artists" VALUES (63, 'Rona Hartner', '', 'Paris / France', 'ph_rona_hartner', '', '', 'http://www.myspace.com/ronahartnercrew', '', 'Harmonia Mundi / Delalune', 'Rona Hartner, la belle tornade venue de l’Est sait tout faire : jouer la comédie, danser, peindre et... chanter! Sur scène, cette princesse des Balkans, découverte dans le film « Gadjo Dilo » de Tony Gatlif, est tout aussi phénoménale. Pourvue d’une aisance naturelle et d’un fort charisme, elle n’a besoin d’aucun préambule pour communiquer de façon complice et joyeuse avec son public.');
INSERT INTO "artists" VALUES (64, 'Little Tune', '', 'Grenoble / France', 'ph_little_tune', '', 'http://www.facebook.com/littletune', 'http://www.myspace.com/djlittletune', '', 'Shamanik', 'Hyperactiviste musical depuis le début des années 2000, Little Tune fait ses classes dans les soirées qu’il organise dans les montagnes grenobloises où il fait résonner ses mixes Reggae Dancehall. En 2003, c’est avec son groupe Air Bass Supa Sound (accompagné du scratcheur Vlad et du toaster Zoom) qu’il écume les dates, avant de produire en solo « Diver’sillons » (2005), CD compilemixtape sur laquelle il exprime tous ses talents sur platine vinyle. Parallèlement animateur de l’émission reggae « Don du Son » sur Radio Grésivaudan, il prend également part 3 années consécutives au festival Interculturel de Mostar (Bosnie) ou il anime des workshops, enseigne le DJing, et joue des dj set lors du Festival. C''est le début d''une belle aventure en tant qu''électron libre éclectique puisque Little Tune se démarque par ses mixes alliant différents styles musicaux. Il joue le plus souvent en solo mais travaille aussi avec des chanteurs reggae / ragga hip hop tels que Patko, Bobo J, Donovan Levy, Manuelouzair et joue également dans des soirées à programmation dub, reggae, ragga hip hop, dubstep, breakbeat & jungle, ainsi que des sets de musiques des balkans & d''electroswing. Tout en s''investissant dans son Collectif Shamanik Sound System et les soirées ''Break the Gap'' et ''Balkan Breaks'', il forme en 2008 ''Les Kimisk'' avec le saxophoniste Jibiz, duo qui fera danser différents publics durant 2 ans avec des sets à la carte mêlant jungle, hip hop ou funk-disco.  Avec plus de 800 dates au compteur en France et à l’étranger, Dj Little Tune a fait vibrer les dancefloors au coté de Sizzla, General Levy, Brain Damage, Mala, The Unik, Invasian Krew Killah, Gerard Baste, Joke, Dj Suspect, Interlope, General Hydrophonik, Radix, Kenei, Opti, Algo Rythmik, Government 4000, Les Enfants 2 la Basse, Docteur Ring Ding, Guiding Star, Jahbass, Dj Kafra, Dj Kayalik, Dj Goodka et des centaines d’autres ! Poursuivant sa mission d’ambianceur infatigable, il régale actuellement la scène grenobloise avec ses résidences mensuelles au Drak-Art et à la Bobine, des lives avec le chanteur reggae dancehall Patko ou encore les rappeurs Kespar et Zoommanuel et travaille sur un nouvel album de bootlegs originaux et terriblement efficaces. DJ Little Tune continue de propager les sourires et secouer les dancefloors grace à ses mixes variés et entrainants, toujours accompagnés d''une présence scénique inimitable.');
INSERT INTO "artists" VALUES (65, 'Sa Bat Machines', '', 'Paris / France', 'ph_sa_bat_machine', '', 'http://www.facebook.com/sabatmachines', 'http://www.myspace.com/sabatmachines', '', 'Kiosk / Destpub', 'Sa bat‘ Machines est un producteur français. Sa musique résulte de la fusion du jazz avec une touche de mélopée klezmer et d’un dustep dynamique. Il combine les thèmes gitans avec le feeling de l’océan Indien et basses synthétiques grasses stridentes. Records Kiosk est son label français basé à Paris et commence à publier ses morceaux en 2008 sur la compilation « Force entrée vol. 1 », puis sur vinyles, kiosque 13, kiosque 16. Police in Helicopter Records publie « The Balsam of the tiger ». Six Degrees Records publie « Valium Gitan Actually Force Coming Vol. 2 » avec Parker.');
INSERT INTO "artists" VALUES (66, 'Son of Kick', '', 'UK', 'ph_son_of_kick', 'http://www.artik-unit.com/artists/son-of-kick/', 'http://www.facebook.com/sonofkick', 'http://www.myspace.com/sonofkick', '', 'Way Way Records / Equinox', 'Son of Kick, producteur, Dj, est un artiste complet, dont le nom résonne aujourd’hui de Berlin à Brooklyn. Après des collaborations avec de nombreux labels, c’est le fameux EP « Guacha » sorti chez Equinox et le clip qui feront grand bruit. S.O.K. revient aujourd’hui avec le single « Playing the Villain » paru en avril dernier chez MUTI Music. Lors de festivals, il croise la route d’artistes tels que Bar 9, Beat Torrent, Diplo, Laurent Garnier, Roots Manuva, Scratch Perverts, Bar Noize, Distance, Baobinga, Detroit Grand Pubahs, Foreign Beggars, et d’autres … SOK est également à la tête de son propre label, Way Way Records, co-produit un LP aux côtés du Dj et producteur français Simbad, travaille sur une paire de remixs et un projet acoustique : « Allover », avec Alice Gobets.');
INSERT INTO "artists" VALUES (67, 'Dubmentalist', '', 'St Etienne / France', 'ph_dubmentalist', '', 'http://www.facebook.com/dubmentalist', '', '', 'Kosmo-K Records', 'Dubmentalist, (Kosmo- K records) offre un live dub-dubstep à base de woobles mentales, percus deeps et beats groovys accompagnés de mélodies orientales. Dès 2005, il commence à produire tracks et lives de break, jungle, D&B, dans le mouvement free-party mais aussi des selecta dub et hip-hop autour de Lyon jusqu’en 2009 : le début du « Dubmentalism ». Depuis 2010, il enchaine les sorties notamment chez AFK Dubstep aux cotés de Silent Frequencies, Altazer, mais aussi en distribution libre chez O.B.I. prod, HiQDubz et Kamikaz CrossFader.');
INSERT INTO "artists" VALUES (68, 'ADD Siméon', '', 'UK', 'ph_add_simeon', '', 'http://www.facebook.com/somethingroovy', 'http://www.myspace.com/somethingroovy', '', 'Somethin Groovy', 'La carrière de Dj d’Addsimeon commence dans les raves « Techno warehouse » de Londres au milieu des années 90. A présent basé dans la ville branchée de Brighton en Angleterre, il s’est associé à Iaindub et à Claire, sa partenaire de longue date, pour former le collectif artistique somethingroovy. Il partage ses sons incroyables et éclectiques dans beaucoup d’évènements en Gande-Bretagne et en Europe, dont Ozora, Gade, Glastonbury, Cosmo, Wildthings, Acid Monkey et Freak Bazaar pour n’en citer que quelques-uns. Ses performances ont toujours une bonne partie de basse... et le sens de l’humour. Attendez-vous donc à un set joyeux allant de l’électro upbeat groovy au dub psychédélique insolite, et au-delà !');
INSERT INTO "artists" VALUES (69, 'Shulman', '', 'Israël', 'ph_shulman', 'http://www.shulman.info', 'http://www.facebook.com/shulman.info', 'http://www.myspace.com/yanivshulman', '', 'Aleph Zero', 'Le projet Shulman, composé de Yaniv Shulman et de plus tard par Omri Harpaz, est considéré comme l’un des groupes leaders de la scène psychédélique chillout et ambient et ont joué dans de grands festivals du monde entier. La musique de Shulman est construite de couches organiques soutenues par des harmonies riches en constante évolution. Shulman ont sorti 3 albums et de nombreuses publications sur des compilations par des labels de premier plan à travers le monde. Ils produisent leur album sur le label avant-gardiste Aleph Zero. Shulman a collaboré avec de nombreux artistes dont des géants de la world music : Omar Faruk Tekbilek et Steve Shehan, Bluetech, Ishq, Lee Triffon et beaucoup d’autres. Des morceaux de Shulman ont été remixés par de célèbres artistes tels que Bluetech, Ishq, Carbon Based Lifeforms, Anahata et d’autres.');
INSERT INTO "artists" VALUES (70, 'Sleeping Forest', '', 'Chambéry / France', 'ph_sleeping_forest', 'http://www.lunarave.com/sleepingforest', '', '', '', 'Hadra / Psynap''s', 'C’est dans son enfance que Lisa-Marine découvre la musique à travers l’apprentissage du piano classique. En grandissant elle entre dans l’univers Rock, comme guitariste/claviériste dans un groupe de rock psychédélique chambérien. Quelques années plus tard, au hasard des rencontres, Sleeping Forest découvre le nouveau monde de la musique électronique, riche de nouvelles sonorités, elle trouve enfin les outils lui permettant de s’exprimer librement. Après de nombreuses collaborations avec LunaRave, elle décide enfin de vous proposer un live ambient bien à elle, interprété avec son instrument fétiche, le clavier !');
INSERT INTO "artists" VALUES (71, 'Vanessa', '', 'Tahïti', 'ph_vanessa', 'http://www.mahanabaylabel.com', 'http://www.facebook.com/mahana.label', 'http://www.myspace.com/mahanabaylabel', '', 'Mahana Bay Label', 'Vanessa alias Arketype Project, artiste Polynésienne qui se produit sur les scènes Européennes et du Pacifique Sud depuis 2002, a aussi crée Mahana Bay, label spécialisé dans les musiques actuelles. Vanessa crée un univers en explorant un monde ou les influences ethniques prédominent. Très imprégnée de ses racines polynésiennes et de l’Orient, Vanessa nous charme en nous entraînant dans un voyage musical aux rythmes tribaux, trance, down-tempo, ambient, trip-hop et rock-électro. Fusion des styles qui ondoient de la réalité brûlante à la réalisation de l’imaginaire le plus intemporel, elle enchante l’espace avec une force hypnotique en glissant d’un univers à l’autre avec maîtrise.');
INSERT INTO "artists" VALUES (72, 'Khaled Ben Yahia', '', 'Tunisie', 'ph_khaled_ben_yahia', 'http://www.khaledbenyahia.music.free.fr', 'http://www.facebook.com/khaled.benyahia.79', 'http://www.myspace.com/khaledbenyahia', '', 'Mahana Bay Label', 'Dès son plus jeune âge, Khaled Ben Yahia est bercé par la musique. A la fin de ses études musicales au Conservatoire en 1987, la presse le salue comme l’un des meilleurs luthistes de sa génération. Avant cette date déjà, il affine son profil comme l’un des meilleurs interprêtes du Oud et comme compositeur. En 1998 il participe à la Biennale de la Danse de Lyon (concert à l’Opéra avec Lotfi Bouchnak). S’ensuit une carrière d’Oudiste solo. En concert Khaled joue aussi bien des pièces du repertoire traditionnel que ses propres compositions. Tout ce travail alimente la sortie de l’album « Wissal » en 2003. En 2008 et 2009 les créations musicales et collaborations artistiques de Kahled Benyahia se multiplient : Bouhour al Ichk, HiJazz et des dizaines de concerts en solo aux quatres coins du monde.');
INSERT INTO "artists" VALUES (73, 'B-Brain', '', 'Grenoble / France', 'ph_b.brain', 'http://www.hadra.net', '', 'http://www.myspace.com/drbbrain', '', 'Hadra', 'B-Brain fait son entrée dans le monde de la nuit comme décorateur scénographe et organisateur de soirées free-parties en rejoignant un sound system techno acid house du sud de la France. Ses mixes sont depuis lors composés d’un mélange éclectique oscillant entre ses influences reggae et dub. En 2010, toujours activiste de la Hadra décoration team et des stages de Djing, il intègre le label Hadra Records et nous offre des Dj sets aux rythmes et aux sonorités planantes. Il travaille aussi son projet B-Brain Live qui promet de faire plaisir aux anciens de la Jungle et du Breakbeat!');
INSERT INTO "artists" VALUES (74, 'VRX-Digitron Sound System', '', 'Croatie', 'ph_vrx-digitron_sound_system', '', '', 'http://www.myspace.com/digitronsoundsystem', '', 'JFX Dubstore', 'Actuellement en plein voyage dub, commencé il y a 10 ans avec le groupe Radikal Dub kolektiv et qui a dérivé entre les voies anarchique / punk / squat / contre-culture. Avec des années actives sur la scène croate à se battre contre des moulins à vent, et avec amour pour le dub digital, ils ont formé et crée le premier sound system qui a traversé les Balkans! L’intention de VRX- Digitron Sound System était d’apporter de la fraîcheur à cette partie de l’Europe qui n’a pas eu l’occasion d’accéder, à cette culture, à cette musique. Aujourd’hui c’est avec Musicwise Digitron dubz qu’ils viendont nous voir. Avec leur sonorités proche d’un dub Steppas anglais, mais influencées par différents courants électro et acoustiques qui sont, pour eux, de profondes expériences du subconscient humain, ils viendront nous communiquer leur productions réalisées sur Jfx dubstore et Digitron records.');
INSERT INTO "artists" VALUES (75, 'Digidep', '', 'Vienne / France', 'ph_digidep', 'http://www.hadra.net', 'http://www.facebook.com/digidep', '', '', 'Hadra', 'A la fois auteur, compositeur et interprète de musique électronique, le projet Digidep, incarné par Arash Kian, est un savant mélange entre trip-hop, IDM et break-beat. Egalement influencé par la trance depuis son entrée sur le label Hadra Records, Digidep est à la croisée des styles et son live fédère ainsi tous les publics. Ambiances indus et psychédéliques, passages survoltés et planants, ingrédients d’une musique précise et soignée, aussi bien dansante que méditative!');
INSERT INTO "artists" VALUES (76, 'Uzul', '', 'Lyon / France', 'ph_uzul', 'http://www.artik-unit.com/artists/uzul/', 'http://www.facebook.com/pages/UZUL/88338462818', 'http://www.myspace.com/uzulprod', '', 'JFX Dubstore', 'Fondateur et créateur des samples & textures électroniques du célèbre groupe Kaly Live Dub, Stéphane Bernard alias Uzul présente aujourd’hui un live dubstep dans lequel il intègre les techniques et effets qui ont fait la renommée du dub. Ses compositions basées sur la pression des infra basses et la caisse claire prédominante l’ont naturellement lié au dubstep à sa sortie des banlieues londoniennes. Une monstrueuse énergie, des beats groovy, des fréquences abyssales … c’est là le fil conducteur qui a rendu le son d’UZUL reconnaissable entre tous.');
INSERT INTO "artists" VALUES (77, 'DJ Nod', '', 'UK', 'ph_dj_nod', 'http://www.djnod.net', 'http://www.facebook.com/nodsamadhi', '', '', '', 'Nod a commencé ses explorations de la musique électronique en écoutant le rock torturé psychédéliqie d’Ozric Tentacles. Au fil des ans, ses oreilles ont traversé de nombreuses variétés de sons allant du dub au trip hop au drone. Après avoir découvert les joies des basses du dubstep, il a aidé à organiser le premier événement mensuel dubstep de la ville d’Asheville (USA). Devenu connu pour ses larges sélections psychédéliques et ses mixes lisses et propres, il a commencé la diffusion des bonnes basses lors de manifestations à travers des soirées psychédéliques aux États-Unis et, avec son récent déménagement à Londres. Nod réside actuellement à Brixton, absorbant les basses au sud de Londres et crée des bruits étranges dans le studio.');
INSERT INTO "artists" VALUES (78, 'Gino', '', 'UK', 'ph_gino', 'http://www.vimeo.com/karmadvision', 'http://www.facebook.com/julien.jamarroquai', 'http://www.myspace.com/karmadvision', '', 'Balkan Sonik', 'Grand adepte des musiques électroniques et en particulier la Trance, Gino a commencé à chercher un nouveau son en venant s’installer à Londres. Très sensible aux arts gypsy depuis toujours et après une longue recherche dans ces domaines, Gino découvre des artistes comme [Dunkelbunt], Parov Stelar ou encore Caravan Palace qui ont réussi à rassembler ses sensibilités musicales. Il commence donc à se monter une collection de Cds et il les pousse aux platines. Au bout d’un an, il se lance dans l’organisation d’une soirée mensuelle du coté de Brixton, Balkan Sonik avec Fred Balkayou, Dj de longue date. Ces soirées connaissent un certain succès depuis quelques années maintenant et Gino a trouvé son style. Rencontre fiévreuse entre un NéoSwing déjanté et les trompettes d’un « Caravan Carnage »!');
INSERT INTO "artists" VALUES (79, 'Itchy & Scratchy', '', 'Cergy / Grenoble / France', 'ph_itchi', '', 'http://www.facebook.com/itchyscratchy.show', '', '', '', 'Itchy & Scratchy, c’est la rencontre (presque) hasardeuse entre un mordu des rythmes minimalistes, Itchy et un féru des gros BPM D’nB, Scratchy. Dans un univers allant de la Minimal joyeuse à la Psy-gressive cosmique, en passant par la Drum intelligente jusqu’à celle de gros truands !!! Un point commun : LE DUBSTEP riche en puissance sonore, qui te fait voyager là où tu n’as encore jamais mis les pieds !!! Le début d’une nouvelle ère commence, là où le commercial atteint même nos plus petites bourgades ! Une ère de dingueries, une ère de singeries, une ère légitimement attendu par vos oreilles en dépression vibrante de voyages sonores ! POING levé, capuche remonté, le Putsh approche ...');
INSERT INTO "artists" VALUES (80, 'G Point', '', 'Lyon / France', 'ph_dj_g_point', '', '', '', '', '', 'G Point découvre la techno en 96 au travers des raves organisées dans les hangars de la région lyonnaise. Il se passionne de suite pour les soirées et festivals techno et va rapidement investir dans des platines vinyles pour assouvir sa passion. Avec l’association Electro Clust il organise quelques soirées sur Lyon au début des années 2000 (monde à l’envers, pez ner...). C’est en 2006 qu’il va découvrir la trance en allant au Boom et va tomber amoureux de la Progressive, aux sonorités parfois assez proche de la techno. Son style est une minimale techno envoutante et hypnotique qui vous éveillera tout en douceur pour bien commencer la journée.');
INSERT INTO "artists" VALUES (81, 'DJ Zen aka Astral Waves', '', 'Canada', 'ph_dj_zen', 'http://www.altar-records.com', 'http://www.facebook.com/DjZen', 'http://www.myspace.com/astralwavesmusic', '', 'Altar Records', 'Dj Zen est né en France et habite au Québec depuis 1996. Très jeune, il fut immergé dans l’univers de la musique surtout grâce à son père qui était fan de Jean-Michel Jarre et Vangelis. Depuis 2002 il compose de la musique électronique sous les pseudos de Dj Zen et Astral Waves et il dirige le label Altar Records qu’il a créé en 2009.');
INSERT INTO "artists" VALUES (82, 'Nova', '', 'UK', 'ph_nova', 'http://www.ultimae.com/en/deejays/nova/index.html', '', 'http://www.myspace.com/nova_music', '', 'Ultimae Records', 'Basé à Londres, Dj, promoteur et journaliste musical, Massimo Terranova alias Nova est un sélecteur de sons prolifiques à la pointe de la scène musicale ambiante / electronica depuis 2000. Nova apparaît comme résident chill-out Dj dans les clubs les plus célèbres et des événements au Royaume-Uni et à l’étranger. Son mélange impeccable de mixture ambient, world music, IDM, downtempo et de textures dub, dans un style éclectique pur de Londres, ont fait de lui un véritable talent recherché dans le monde des Dj.');
INSERT INTO "artists" VALUES (83, 'MKF', '', 'Grenoble', 'ph_mkf', 'http://www.mkf.mustradem.com', 'http://www.facebook.com/pages/MKF/110880395601656', '', '', 'Mustradem', 'MKF (Musical Kinematic Factory) fait le lien entre les musiques traditionnelles et les musiques électroniques, fusionne instruments de lutherie et le bit des machines et rapproche les parquets de bal d’hier et le Dance floor d’aujourd’hui.Tels trois Djs avec leur « button box », ils travaillent « a mano » leur son, jouant de leurs claviers comme de « faders ». Bois, métal, cuir, puces électroniques sont la materia prima de cette nouvelle création et ces trois musiciens grenoblois au talent reconnu la mixent généreusement de leurs six mains.Avec subtilité et élégance, MKF esquisse les contours d’un univers musical particulier qui résonne bien au-delà du temps et des frontières géographiques.');
INSERT INTO "artists" VALUES (84, 'M&M\''s', '', 'Portugal', 'ph_mms', '', '', 'http://www.myspace.com/djmnms', '', 'Elecktrik Dream', 'Depuis son plus jeune âge, Martim Martins alias M&Ms est un amateur de musique. Ses principales influences sont : Pink Floyd, The Sonic Youth, The Swans, Dead Kennedys, Diamanda Galas et The Pogues. Depuis sa première expérience en tant que Dj en 2004, Martim n’a jamais cessé de jouer. Il travaille régulièrement avec des promoteurs comme Quest 4 Goa, Omium, synergic Minds, Good Trance, Crystal Matrix, et d’autres. Depuis, il joue tous les genres Downtempo en tant que Dj et son Dj set va de Psychill Freestyle Electronica, Minimal, Ethnique, Nujazz, Groove. C’est au cours de l’Utopia After du Boom 2006 qu’il a été invité à rejoindre Electrik Dream. Actuellement sa sélection de piste va du accoustic chill, à Cinematic et à l’ambient électronic.');


INSERT INTO "sets" VALUES (1, 1346361660, 1346286180, 'DJ', 1, 'Main stage');
INSERT INTO "sets" VALUES (2, 1346368980, 1346284800, 'Live', 2, 'Main stage');
INSERT INTO "sets" VALUES (3, 1346371200, 1346371260, 'DJ', 3, 'Main stage');
INSERT INTO "sets" VALUES (4, 1346374860, 1346371380, 'DJ', 4, 'Main stage');
INSERT INTO "sets" VALUES (5, 1346382180, 1346371440, 'Live', 5, 'Main stage');
INSERT INTO "sets" VALUES (6, 1346385840, 1346371560, 'DJ', 6, 'Main stage');
INSERT INTO "sets" VALUES (7, 1346393160, 1346371620, 'Live', 7, 'Main stage');
INSERT INTO "sets" VALUES (8, 1346396820, 1346371680, 'Live', 8, 'Main stage');
INSERT INTO "sets" VALUES (9, 1346400480, 1346371740, 'Live', 9, 'Main stage');
INSERT INTO "sets" VALUES (10, 1346404140, 1346371800, 'DJ', 10, 'Main stage');
INSERT INTO "sets" VALUES (11, 1346407800, 1346371860, 'Live', 11, 'Main stage');
INSERT INTO "sets" VALUES (12, 1346411460, 1346371920, 'Live', 12, 'Main stage');
INSERT INTO "sets" VALUES (13, 1346415120, 1346372040, 'DJ', 13, 'Main stage');
INSERT INTO "sets" VALUES (14, 1346422440, 1346372100, 'DJ', 14, 'Main stage');
INSERT INTO "sets" VALUES (15, 1346426100, 1346372160, 'Live', 15, 'Main stage');
INSERT INTO "sets" VALUES (16, 1346429760, 1346372280, 'DJ', 16, 'Main stage');
INSERT INTO "sets" VALUES (17, 1346444400, 1346372520, 'Gig', 17, 'Main stage');
INSERT INTO "sets" VALUES (18, 1346451720, 1346372580, 'Live', 18, 'Main stage');
INSERT INTO "sets" VALUES (19, 1346455380, 1346371200, 'Live', 19, 'Main stage');
INSERT INTO "sets" VALUES (20, 1346457600, 1346457660, 'Live', 20, 'Main stage');
INSERT INTO "sets" VALUES (21, 1346461260, 1346457780, 'DJ', 21, 'Main stage');
INSERT INTO "sets" VALUES (22, 1346468580, 1346457840, 'Live', 22, 'Main stage');
INSERT INTO "sets" VALUES (23, 1346472240, 1346457900, 'Live', 23, 'Main stage');
INSERT INTO "sets" VALUES (24, 1346475900, 1346457960, 'Live', 24, 'Main stage');
INSERT INTO "sets" VALUES (25, 1346479560, 1346458080, 'DJ', 25, 'Main stage');
INSERT INTO "sets" VALUES (26, 1346486880, 1346458140, 'Live', 26, 'Main stage');
INSERT INTO "sets" VALUES (27, 1346490540, 1346458200, 'Live', 27, 'Main stage');
INSERT INTO "sets" VALUES (28, 1346494200, 1346458320, 'DJ', 28, 'Main stage');
INSERT INTO "sets" VALUES (29, 1346501520, 1346458380, 'DJ', 29, 'Main stage');
INSERT INTO "sets" VALUES (30, 1346505180, 1346458440, 'Live', 30, 'Main stage');
INSERT INTO "sets" VALUES (31, 1346508840, 1346458560, 'DJ', 31, 'Main stage');
INSERT INTO "sets" VALUES (32, 1346516160, 1346458620, 'Live', 32, 'Main stage');
INSERT INTO "sets" VALUES (33, 1346530800, 1346458920, 'Gig', 33, 'Main stage');
INSERT INTO "sets" VALUES (34, 1346538120, 1346458980, 'Live', 34, 'Main stage');
INSERT INTO "sets" VALUES (35, 1346541780, 1346457600, 'Live', 35, 'Main stage');
INSERT INTO "sets" VALUES (36, 1346544000, 1346544060, 'Live', 36, 'Main stage');
INSERT INTO "sets" VALUES (37, 1346547660, 1346544120, 'Live', 37, 'Main stage');
INSERT INTO "sets" VALUES (38, 1346551320, 1346544180, 'Live', 38, 'Main stage');
INSERT INTO "sets" VALUES (39, 1346554980, 1346544240, 'Live', 39, 'Main stage');
INSERT INTO "sets" VALUES (40, 1346558640, 1346544300, 'DJ', 40, 'Main stage');
INSERT INTO "sets" VALUES (41, 1346562300, 1346544360, 'Live', 41, 'Main stage');
INSERT INTO "sets" VALUES (42, 1346565960, 1346544420, 'Live', 42, 'Main stage');
INSERT INTO "sets" VALUES (43, 1346569620, 1346544480, 'Live', 43, 'Main stage');
INSERT INTO "sets" VALUES (44, 1346573280, 1346544600, 'DJ', 44, 'Main stage');
INSERT INTO "sets" VALUES (45, 1346580600, 1346544660, 'Live', 45, 'Main stage');
INSERT INTO "sets" VALUES (46, 1346584260, 1346544720, 'Live', 46, 'Main stage');
INSERT INTO "sets" VALUES (47, 1346587920, 1346544780, 'Live', 47, 'Main stage');
INSERT INTO "sets" VALUES (48, 1346591580, 1346544900, 'DJ', 48, 'Main stage');
INSERT INTO "sets" VALUES (49, 1346598900, 1346544960, 'Live', 49, 'Main stage');
INSERT INTO "sets" VALUES (50, 1346602560, 1346545020, 'Live', 50, 'Main stage');
INSERT INTO "sets" VALUES (51, 1346606220, 1346545080, 'Live', 51, 'Main stage');
INSERT INTO "sets" VALUES (52, 1346355000, 1346360400, 'Live', 52, 'Alternative stage');
INSERT INTO "sets" VALUES (53, 1346360400, 1346365800, 'Live', 53, 'Alternative stage');
INSERT INTO "sets" VALUES (54, 1346365800, 1346290200, 'Live', 54, 'Alternative stage');
INSERT INTO "sets" VALUES (55, 1346376600, 1346387400, 'DJ', 55, 'Alternative stage');
INSERT INTO "sets" VALUES (56, 1346387400, 1346392800, 'Live', 56, 'Alternative stage');
INSERT INTO "sets" VALUES (57, 1346392800, 1346403600, 'DJ', 57, 'Alternative stage');
INSERT INTO "sets" VALUES (58, 1346403600, 1346418000, 'DJ', 58, 'Alternative stage');
INSERT INTO "sets" VALUES (59, 1346418000, 1346428800, 'DJ', 59, 'Alternative stage');
INSERT INTO "sets" VALUES (60, 1346428800, 1346439600, 'DJ', 60, 'Alternative stage');
INSERT INTO "sets" VALUES (61, 1346439600, 1346445000, 'Live', 61, 'Alternative stage');
INSERT INTO "sets" VALUES (62, 1346452200, 1346373000, 'Gig', 62, 'Alternative stage');
INSERT INTO "sets" VALUES (63, 1346459400, 1346463000, 'Gig', 63, 'Alternative stage');
INSERT INTO "sets" VALUES (64, 1346463000, 1346466600, 'DJ', 64, 'Alternative stage');
INSERT INTO "sets" VALUES (65, 1346466600, 1346472000, 'Live', 65, 'Alternative stage');
INSERT INTO "sets" VALUES (66, 1346472000, 1346477400, 'Live', 66, 'Alternative stage');
INSERT INTO "sets" VALUES (67, 1346477400, 1346484600, 'Live', 67, 'Alternative stage');
INSERT INTO "sets" VALUES (68, 1346484600, 1346493600, 'DJ', 68, 'Alternative stage');
INSERT INTO "sets" VALUES (69, 1346493600, 1346499000, 'Live', 69, 'Alternative stage');
INSERT INTO "sets" VALUES (70, 1346499000, 1346504400, 'Live', 70, 'Alternative stage');
INSERT INTO "sets" VALUES (71, 1346504400, 1346509800, 'DJ', 71, 'Alternative stage');
INSERT INTO "sets" VALUES (72, 1346512500, 1346517000, 'Gig', 72, 'Alternative stage');
INSERT INTO "sets" VALUES (73, 1346517000, 1346522400, 'Live', 73, 'Alternative stage');
INSERT INTO "sets" VALUES (74, 1346522400, 1346531400, 'DJ', 74, 'Alternative stage');
INSERT INTO "sets" VALUES (75, 1346538600, 1346457600, 'Live', 75, 'Alternative stage');
INSERT INTO "sets" VALUES (76, 1346544000, 1346549400, 'Live', 76, 'Alternative stage');
INSERT INTO "sets" VALUES (77, 1346549400, 1346556600, 'DJ', 77, 'Alternative stage');
INSERT INTO "sets" VALUES (78, 1346556600, 1346563800, 'DJ', 78, 'Alternative stage');
INSERT INTO "sets" VALUES (79, 1346563800, 1346569200, 'Live', 79, 'Alternative stage');
INSERT INTO "sets" VALUES (80, 1346569200, 1346576400, 'DJ', 80, 'Alternative stage');
INSERT INTO "sets" VALUES (81, 1346576400, 1346583600, 'Live', 81, 'Alternative stage');
INSERT INTO "sets" VALUES (82, 1346583600, 1346592600, 'DJ', 82, 'Alternative stage');
INSERT INTO "sets" VALUES (83, 1346592600, 1346601600, 'Gig', 83, 'Alternative stage');
INSERT INTO "sets" VALUES (84, 1346601600, 1346608800, 'DJ', 84, 'Alternative stage');
